import random

EXERCISES = [
	'10 Burpees',
	'10 Calf Raises (toes pointed in)',
	'10 Calf Raises (toes pointed out)',
	'10 Calf Raises (toes straight)',
	'15 Calf Raises (toes pointed in)',
	'15 Calf Raises (toes pointed out)',
	'15 Calf Raises (toes straight)',
	'20 Calf Raises (toes pointed in)',
	'20 Calf Raises (toes pointed out)',
	'20 Calf Raises (toes straight)',
	'10 Push-ups',
	'10 Short Bridges',
	'10 Side Lunges',
	'10 Superman',
	'100 Jumping Jacks',
	'15 Burpees',
	'15 Regular Push-ups',
	'15 Hands pointed in Push-ups',
	'16 Front Lunges',
	'16 Rear Lunges',
	'20 Back Lunges',
	'20 Bent Knee Side Leg Raises',
	'20 Burpees',
	'20 Butterfly Sit-ups',
	'20 Butterfly side leg raises',
	'20 Crunches',
	'20 Single Leg Donkey Kicks',
	'20 Firehose Leg Raises',
	'20 Front Lunges',
	'20 Good mornings',
	'20 High Knees',
	'20 Jump Squats',
	'20 Jumping Jacks',
	'20 Knee to Elbow Bicycles',
	'20 Kneel-ups',
	'20 Mountain Climbers',
	'20 Push-ups',
	'20 Russion Twists',
	'20 Short Bridges',
	'20 Short Bridges Knees to chest',
	'20 Short Bridges kick up',
	'20 Side Lunges',
	'20 Side leg raises',
	'20 Standing Hip Abductions',
	'20 Superman',
	'20 Tricep Dips',
	'25 Burpees',
	'30 Bent knee side leg raises',
	'30 Butterfly Sit-ups',
	'30 Butterfly side leg raises',
	'30 Crunches',
	'30 Single Leg Donkey Kicks',
	'30 Firehose Leg Raises',
	'30 Flutter Kicks',
	'30 Front Elevated Mountain Climbers',
	'30 Good mornings',
	'30 High Knees',
	'30 Jump Squats',
	'30 Jumping Jacks',
	'30 Knee to Elbow Bicycles',
	'30 Kneel-ups',
	'30 Leg Raises (laying on back)',
	'30 Mountain Climbers',
	'30 Russian Twists',
	'30 Short Bridges',
	'30 Side leg raises',
	'30 Squats',
	'30 Standing Hip Abductions',
	'30 Tricep Dips',
	'40 Butterfly Sit-ups',
	'40 Single Leg Donkey Kicks',
	'40 Good mornings',
	'40 High Knees',
	'40 Jumping Jacks',
	'40 Knee to Elbow Bicycles',
	'40 Mountain Climbers',
	'50 High Knees',
	'50 Jumping Jacks',
	'60 High Knees',
	'80 High Knees',
	'80 Jumping Jacks',
	'5 Dive Through Push-ups',
	'10 Dive Through Push-ups',
	'10 Regular Push-ups',
	'20 Regular Push-ups',
	'10 Diamond Push-ups',
	'15 Dive Through Push-ups',
	'10 Pre-Handstand Toe Lift',
	'15 Pre-Handstand Toe Lift',
	'10 Pre-Handstand Toe Lift, on elbows',
	'15 Pre-Handstand Toe Lift, on elbows',
	'20 Kneeling Extended Leg Raises',
	'30 Kneeling Extended Leg Raises',
	'10 Kneeling Extended Leg Raises',
	'5 Double Leg Donkey Kick',
	'10 Double Leg Donkey Kick',
	'15 Double Leg Donkey Kick',
	'10 Swimmers',
	'16 Swimmers',
	'20 Swimmers',
	'20 plank shoulder taps',
	'25 plank shoulder taps',
	'30 plank shoulder taps',
	'10 plank side-steps',
	'6 plank side-steps',
	'12 plank side-steps',
	'10 side laying hip adductions',
	'20 side laying hip adductions',
	'30 side laying hip adductions',
	'10 Hooked thumb arm raises shoulder opener',
	'15 Hooked thumb arm raises shoulder opener',
	'20 Hooked thumb arm raises shoulder opener',
	'15 Hollow Rocks',
	'20 Hollow Rocks',
	'10 Hollow Rocks'
 ]

BLOCKS = [
	'10 Butterfly Pelvic Tilt',
	'10 Straddle Pelvic Tilt',
	'15 Butterfly Pelvic Tilt',
	'15 Straddle Pelvic Tilt',
	'10 Parallette Dips',
	'15 Parallette Dips',
	'20 Parallette Dips',
	'10 Parallette Push-ups',
	'10 Parallette Dive Through Push-ups',
	'5 Parallette Dive Through Push-ups',
	'10 Parallette Skullcrusher Push-ups',
	'15 Parallette Skullcrusher Push-ups',
	'15 Parallette Tucked L-sit Single Leg Toe Taps',
]

MINI_BAND = [
	'10 Side leg raises with Mini band',
	'10 Bent knee leg raises with Mini band',
	'10 Butterfly side leg raises with Mini band',
	'20 Side leg raises with Mini band',
	'20 Bent knee leg raises with Mini band',
	'20 Butterfly side leg raises with Mini band',
	'10 Short Bridges with mini band',
	'20 Short Bridges with mini band',
	'30 Short Bridges with mini band',
	'20 Mini Band Tricep Rows',
	'30 Mini Band Tricep Rows',
	'20 Reverse Grip Single-Arm Curl and Row',
	'30 Reverse Grip Single-Arm Curl and Row',
	'20 Mini Band Side Lateral Arm Raise',
	'30 Mini Band Side Lateral Arm Raise',
	'20 Triceps Presses/extensions',
	'30 Triceps Presses/extensions',
	'20 Lat Pull-Downs',
	'30 Lat Pull-Down',
	'20 Horizontal Arm Extensions',
	'30 Horizontal Arm Extensions',
	'20 Rear Arm Extensions',
	'30 Rear Arm Extensions',
	'20 Standing Hip Abductions (with Mini band)',
	'30 Standing Hip Abductions (with Mini band)',
	'20 Mini Band Squatting Side Steps',
	'30 Mini Band Squatting Side Steps',
	'10 V Rows',
	'20 V Rows',
	'30 V Rows',
	'40 V Rows',
	'50 V Rows',
	'30 Kneeling Curl',
	'40 Kneeling Curl',
	'20 Single Leg Donkey Kicks w/ Mini Band',
	'30 Single Leg Donkey Kicks w/ Mini Band',
	'40 Single Leg Donkey Kicks w/ Mini Band',
	'10 Mini Band Deadlift',
	'20 Mini Band Deadlift',
	'30 Mini Band Deadlift',
	'40 Mini Band Deadlift',
	'20 Mini Band Jump Squats',
	'30 Mini Band Jump Squats',
	'20 Kneeling Extended Leg Raises (w/ Mini Band)',
	'30 Kneeling Extended Leg Raises (w/ Mini Band)',
	'10 Kneeling Extended Leg Raises (w/ Mini Band)',
]

RESISTENCE_BAND = [
	'10 Resistence Band Standing Bicep Curls',
	'20 Resistence Band Standing Bicep Curls',
	'10 Resistence Band Reverse Grip Curls',
	'20 Resistence Band Reverse Grip Curls',
	'10 Resistence Band Extended Arm Wrist Flex',
	'20 Resistence Band Extended Arm Wrist Flex',
	'10 Tricep Pull Down (door)',
	'20 Tricep Pull Down (door)',
	'10 Resistence Band Overhead Tricep Pulls',
	'20 Resistence Band Overhead Tricep Pulls',
	'10 Standin Row (door)',
	'30 Standing Row (door)',
	'20 Standin Row (door)',
	'10 Interior Arm Rotations (door)',
	'20 Interior Arm Rotations (door)',
	'10 Exterior Arm Rotations (door)',
	'20 Exterior Arm Rotations (door)',
	'10 Resistence Band Front Arm Raises',
	'20 Resistence Band Front Arm Raises',
	'10 Resistence Band Lateral Arm Raises',
	'20 Resistence Band Lateral Arm Raises',
	'10 Chest Fly (door)',
	'20 Chest Fly (door)',
	'10 Chest Presses (door)',
	'20 Chest Presses (door)',
	'10 Resistence Banc Diagonal Arm Crosses',
	'20 Kneeling Crunches',
	'10 Resistence Band Squats (door)',
	'20 Resistence Band Squats (door)',
	'30 Resistence Band Squats (door)',
	'10 Resistence Band Squats (standing on band)',
	'20 Resistence Band Squats (standing on band)',
	'30 Resistence Band Squats (standing on band)',
	'20 Kneeling Kick backs',
	'25 Kneeling Kick backs',
	'20 Laying Single Leg Kicks',
	'25 Laying Single Leg Kicks',
]

RESITENCE_CIRCLE = [
	'10 side laying hip adductions, w/circle',
	'20 side laying hip adductions, w/circle',
	'30 side laying hip adductions, w/circle',
	'10 lower leg circles',
	'20 lower leg circles',
	'30 lower leg circles',
]
 
HOLDS = [
	'1 Minute Elbow Plank',
	'1 Minute Short Bridge Hold',
	'1 Minute Square Bridge Hold',
	'1 Minute Squat Hold',
	'1 minute plank',
	'1 minute wall sit',
	'2 minute wall sit',
	'2 Minute Squat Hold',
	'30 Second Short Bridge Hold',
	'30 Second Side Plank Per Side',
	'15 Second Side Plank Per Side',
	'10 Second Side Plank Per Side',
	'30 Second Square Bridge Hold',
	'30 Second Superman Hold',
	'30 Second Swan Hold',
	'1 Minute Swan Hold',
	'30 Second Straddle Hold',
	'30 Second Butterfly Hold',
	'1 Minute Straddle Hold',
	'1 Minute Butterfly Hold',
	'30 Second Parallette Tucked L-sit',
	'30 Second Wall Hand-Stand',
	'15 Second Wall Hand-Stand',
	'45 Second Wall Hand-Stand',
]

OTHER_TOYS = [
	'15 Balance Board Squats',
	'30 Balance Board Squats',
	'30 Second Balance Board Plank',
	'1 Minute Balance Board Plank',
	'5 Balance Board Push-ups',
	'10 Balance Board Mountain Climbers',
	'5 Ab Rolls',
	'10 Ab Rolls',
	'10 Yoga ball leg lifts',
	'10 Yoga Ball Sit-up passes',
	'5 Yoga ball overhead squats',
	'10 side laying hip adductions, w/circle',
	'20 side laying hip adductions, w/circle',
	'30 side laying hip adductions, w/circle',
	'10 lower leg circles',
	'20 lower leg circles',
	'30 lower leg circles',
	'Pole shoulder mobility sequence',
	'10 Balance Board Short Bridges',
	'30 Second Elevated Plank',
	'5 Foot elevated Push-ups',
	'30 Second Elbow Pilates ball plank',
	'10 Front Neck crunches',
	'10 Front Neck crunches',
	'10 pole shoulder presses',
	'10 pole shoulder circles',
	'10 pole shoulder raise and lower'
]

num_exercises = input('How many different moves do you want to do?\n')
include_mini_band = input('Include mini band exercises? True or False\n')
include_resistence_band = input('Include long resistence band exercises?\n')
include_blocks = input('Include block exercises?\n')
include_other = input('include other toys?\n')
include_holds = input('Include static hold exercises?\n')
exercises = EXERCISES
if include_mini_band:
	exercises += MINI_BAND
if include_resistence_band:
	exercises += RESISTENCE_BAND
if include_blocks:
	exercises += BLOCKS
if include_holds:
	exercises += HOLDS
if include_other:
	exercises += OTHER_TOYS
print('Your assignment is:\n')
for _ in range(num_exercises):
	move_index = random.randint(0, len(exercises)-1)
	move = exercises[move_index]
	print(' - '+move)

print('\nGood luck!')
