import random

EXERCISES = [
	'1 minute plank',
	'1 minute wall sit',
	'10 Burpees',
	'10 Push-ups',
	'10 Jumping Jacks',
	'10 High Knees',
	'10 Calf Raises (toes straight)',
	'10 Calf Raises (toes pointed in)',
	'10 Calf Raises (toes pointed out)',
	'16 Rear Lunges',
	'15 Burpees',
	'16 Front Lunges',
	'15 Push-ups',
	'15 Push-ups',
	'1 Minute Elbow Plank',
	'2 minute wall sit',
	'20 Back Lunges',
	'20 Burpees',
	'20 Crunches',
	'20 Front Lunges',
	'20 Jump Squats',
	'20 Push-ups',
	'20 Tricep Dips',
	'25 Burpees',
	'30 Crunches',
	'30 Jump Squats',
	'30 Jumping Jacks',
	'30 High Knees',
	'30 Squats',
	'30 Tricep Dips',
	'40 Jumping Jacks',
	'40 High Knees',
	'50 High Knees',
	'50 Jumping Jacks',
	'10 Short Bridges',
	'20 Short Bridges',
	'30 Short Bridges',
	'20 Short Bridges Knees to chest',
	'20 Short Bridges kick up',
	'30 Second Short Bridge Hold',
	'30 Square Bridge Hold',
	'1 Minute Short Bridge Hold'.
	'1 Minute Square Bridge Hold'
	'20 Side Lunges',
	'10 Side Lunges',
	'20 Butterfly Sit-ups',
	'30 Butterfly Sit-ups',
	'40 Butterfly Sit-ups',
	'20 Kneel-ups',
	'30 Kneel-ups',
	'20 Side leg raises',
	'20 Bent Knee Side Leg Raises',
	'20 Butterfly side leg raises',
	'30 Side leg raises',
	'30 Bent knee side leg raises',
	'30 Butterfly side leg raises',
	'20 Donkey Kicks',
	'30 Donkey Kicks',
	'40 Donkey Kicks',
	'20 Firehose Leg Raises',
	'30 Firehose Leg Raises',
	'20 Knee to Elbow Bicycles',
	'30 Knee to Elbow Bicycles',
	'40 Knee to Elbow Bicycles',
	'20 Standing Hip Abductions',
	'30 Standing Hip Abductions',
	'30 Flutter Kicks'.
	'10 Superman',
	'20 Superman',
	'30 Second Superman Hold',
	'30 Leg Raises (laying on back)',
	'30 Russian Twists',
	'20 Russion Twists',
	'30 Mountain Climbers',
	'20 Mountain Climbers',
	'40 Mountain Climbers',
	'30 Front Elevated Mountain Climbers',
	'30 Second Side Plank Per Side',
	'15 Second Side Plank Per Side',
]

RESISTENCE_BAND = [
	'10 Side leg raises with resistence band',
	'10 Bent knee leg raises with resistence band',
	'10 Butterfly side leg raises with resistence band',
	'20 Side leg raises with resistence band',
	'20 Bent knee leg raises with resistence band',
	'20 Butterfly side leg raises with resistence band',
	'10 Short Bridges with resistence band',
	'20 Short Bridges with resistence band',
	'30 Short Bridges with resistence band',
	'20 Tricep Pulls',
	'30 Tricep Pulls',
	'20 Reverse Grip Single-Arm Curl and Row',
	'30 Reverse Grip Single-Arm Curl and Row',
	'20 Side Lateral Arm Raise',
	'30 Side Lateral Arm Raise',
	'20 Triceps Presses/extensions',
	'30 Triceps Presses/extensions',
	'20 Lat Pull-Downs',
	'30 Lat Pull-Down',
	'20 Horizontal Arm Extensions',
	'30 Horizontal Arm Extensions',
	'20 Rear Arm Extensions',
	'30 Rear Arm Extensions',
	'20 Standing Hip Abductions (with resistence band)',
	'30 Standing Hip Abductions (with resistence band)',
	'20 Squatting Side Steps',
	'30 Squatting Side Steps',
	'30 V Rows',
	'40 V Rows',
	'50 V Rows',
	'20 Kneeling Curl',
	'30 Kneeling Curl',
]

num_exercises = input('How many different moves do you want to do?\n')
include_band = input('Include mini band exercises? True or False\n')
if include_band:
	exercises = EXERCISES + RESISTENCE_BAND
else:
	exercises = EXERCISES
print('Your assignment is:\n')
for i in range(num_exercises):
	move_index = random.randint(0, len(exercises)-1)
	move = exercises[move_index]
	print(' - '+move)

print('\nGood luck!')
